#!/usr/bin/env python3
"""
closers.py — the last thing said before the save key. The reason each clip exists.

    python3 persona/closers.py               # write persona/closers.md
    python3 persona/closers.py --append      # add the section to persona/jason-model.md, all [private]
    python3 persona/closers.py --seconds 20  # widen the window

Every clip in this corpus is a replay-buffer save: the speaker heard themselves say
something, thought "that's worth keeping", and hit the key. The buffer holds the
preceding minute, so the START of a clip is lead-up and the END is the line that
earned the save. That is a salience label the speaker applied in the moment, 364
times, and it is the most honest signal in the corpus — better than anything a model
infers about which sentence mattered.

This pulls the final CLOSE_S seconds of each clip's Whisper segments (whole segments,
so a sentence is never cut mid-way) into a dated list. Stdlib only, deterministic.

The same idea generalises: in a check-in app, the moment of submission is the label; in
a journal, the last line before the save. Record what the person marked, not what a
model thinks they meant.
"""
import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
bp = __import__("build-persona")

CLOSE_S = 12.0
# Whisper large-v3 hallucinates these on trailing silence. They are not the closer.
HALLUCINATED = re.compile(r"amara\.org|thank you for watching|thanks for watching|subscribe|"
                          r"^\s*(you|bye|thank you\.?)\s*$", re.I)
SECTION = "## What they saved it for — the closing lines"


def closers(seconds=CLOSE_S):
    """[(date, clip_id, closer_text, clip_len_s)] for every dated clip with segments."""
    import json
    out = []
    for f in sorted((HERE / "corpus").glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        segs = [s for s in (d.get("segments") or []) if not HALLUCINATED.search(s.get("text", ""))]
        if not segs:
            continue
        stem = f.stem
        date = bp.clip_date(stem)
        end = segs[-1].get("end", 0.0)
        tail = [s for s in segs if s.get("end", 0.0) > end - seconds]
        text = " ".join(s.get("text", "").strip() for s in tail).strip()
        text = re.sub(r"\s+", " ", text)
        if len(text.split()) < 3:
            continue
        out.append((date, stem, text, end))
    out.sort(key=lambda r: (r[0] == "undated", r[0], r[1]))
    return out


def render(rows, seconds):
    lines = [f"<!-- closers — the last {seconds:.0f}s of each clip, generated by persona/closers.py "
             f"from {len(rows)} clips. PRIVATE: this is the journal, distilled. -->", "",
             "# What they saved it for", "",
             f"The final {seconds:.0f} seconds of every clip — the line that earned the save key. "
             "One per clip, by date.", ""]
    cur = None
    for date, cid, text, end in rows:
        if date != cur:
            lines += ["", f"## {date}", ""]
            cur = date
        lines.append(f"- {text}  *({end:.0f}s clip)*")
    return "\n".join(lines) + "\n"


def model_section(rows):
    lines = [SECTION, "", "<!-- from persona/closers.py — the last line before the save key, one per clip. "
             "Re-run `closers.py --append` to refresh; it replaces this section only. -->", ""]
    for date, cid, text, end in rows:
        lines.append(f"- \"{text}\" ({date}) [private]")
    return "\n".join(lines) + "\n"


def append_to_model(rows):
    path = HERE / "jason-model.md"
    if not path.is_file():
        sys.exit("no persona/jason-model.md yet — run build-persona.py first")
    text = path.read_text(encoding="utf-8")
    section = model_section(rows)
    if SECTION in text:
        head, _, rest = text.partition(SECTION)
        nxt = re.search(r"^## ", rest, flags=re.M)
        text = head + section + ("\n" + rest[nxt.start():] if nxt else "")
    else:
        text = text.rstrip("\n") + "\n\n" + section
    path.write_text(text, encoding="utf-8")
    print(f"{path.name}: section '{SECTION[3:]}' written ({len(rows)} bullets, all [private])")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=float, default=CLOSE_S)
    ap.add_argument("--append", action="store_true")
    args = ap.parse_args()
    rows = closers(args.seconds)
    if args.append:
        append_to_model(rows)
        return
    out = HERE / "closers.md"
    out.write_text(render(rows, args.seconds), encoding="utf-8")
    words = sum(len(r[2].split()) for r in rows)
    print(f"wrote {out}: {len(rows)} closers, {words} words (the corpus is ~50,000)")


if __name__ == "__main__":
    main()
